# Generated by Django 5.2 on 2025-05-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_customer_municipality_customer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='proveedor',
            field=models.CharField(choices=[('Stickimy', 'Stickimy')], default='Stickimy', max_length=100),
            preserve_default=False,
        ),
    ]
