# Generated by Django 5.1.6 on 2025-09-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_product_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='finish',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Sujeción y Soporte', 'Sujeción y Soporte'), ('Motor y Transmisión', 'Motor y Transmisión'), ('Sistema hidraulico y Neumatico', 'Sistema hidraulico y Neumatico'), ('Bujes y Casquillos', 'Bujes y Casquillos'), ('Sistema de Frenos', 'Sistema de Frenos'), ('Accesorios y Misceláneos', 'Accesorios y Misceláneos')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='imagedos',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='imagetres',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='imageuno',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(choices=[('Acero', 'Acero'), ('Hierro fundido', 'Hierro fundido'), ('Bronce / Latón', 'Bronce / Latón'), ('Aluminio', 'Aluminio'), ('Goma / Poliuretano', 'Goma / Poliuretano'), ('Otro', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='proveedor',
            field=models.CharField(choices=[('Productos Almeyda', 'Productos Almeyda')], max_length=100),
        ),
    ]
