# Generated by Django 5.2.6 on 2025-09-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_remove_product_finish_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('paypal', 'PayPal'), ('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_processed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_requested_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Procesando', 'Procesando'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado'), ('Reembolso_Pendiente', 'Reembolso Pendiente'), ('Reembolsado', 'Reembolsado')], default='Pendiente', max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='imagedos',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='imagetres',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='imageuno',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
