# Generated by Django 5.2.6 on 2025-09-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_order_payment_method_order_refund_processed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente de Pago'), ('Procesando', 'Pago Confirmado - Preparando Envío'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado'), ('Reembolso_Pendiente', 'Reembolso Pendiente'), ('Reembolsado', 'Reembolsado')], default='Pendiente', max_length=25),
        ),
    ]
