# Generated by Django 5.1.6 on 2025-11-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_alter_orderhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='payment_method',
            field=models.CharField(choices=[('bank-transfer', 'Transferencia Bancaria'), ('bank-deposit', 'Depósito en Banco'), ('online-payment', 'Pago en Línea con Tarjetas')], default='bank-transfer', max_length=20),
        ),
    ]
