# Generated by Django 5.1.6 on 2025-11-18 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_alter_orderhistory_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Ej: Casa, Trabajo, Casa de mamá', max_length=50)),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre completo del destinatario')),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=300, verbose_name='Calle y número')),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Colonia')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad/Municipio')),
                ('state', models.CharField(choices=[('AGU', 'Aguascalientes'), ('BCN', 'Baja California'), ('BCS', 'Baja California Sur'), ('CAM', 'Campeche'), ('CHP', 'Chiapas'), ('CHH', 'Chihuahua'), ('COA', 'Coahuila'), ('COL', 'Colima'), ('DIF', 'Ciudad de México'), ('DUR', 'Durango'), ('GUA', 'Guanajuato'), ('GRO', 'Guerrero'), ('HGO', 'Hidalgo'), ('JAL', 'Jalisco'), ('MEX', 'Estado de México'), ('MIC', 'Michoacán'), ('MOR', 'Morelos'), ('NAY', 'Nayarit'), ('NLE', 'Nuevo León'), ('OAX', 'Oaxaca'), ('PUE', 'Puebla'), ('QRO', 'Querétaro'), ('QRO', 'Quintana Roo'), ('SLP', 'San Luis Potosí'), ('SIN', 'Sinaloa'), ('SON', 'Sonora'), ('TAB', 'Tabasco'), ('TAM', 'Tamaulipas'), ('TLX', 'Tlaxcala'), ('VER', 'Veracruz'), ('YUC', 'Yucatán'), ('ZAC', 'Zacatecas')], max_length=3, verbose_name='Estado')),
                ('zipcode', models.CharField(max_length=10, verbose_name='Código postal')),
                ('references', models.TextField(blank=True, null=True, verbose_name='Referencias adicionales')),
                ('is_default', models.BooleanField(default=False, verbose_name='Dirección principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='store.customer')),
            ],
            options={
                'verbose_name': 'Dirección del Cliente',
                'verbose_name_plural': 'Direcciones de Clientes',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='customer_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customeraddress'),
        ),
    ]
