# Generated by Django 5.1.6 on 2025-11-18 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_shippingaddress_name_shippingaddress_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_type', models.CharField(choices=[('cancellation', 'Cancelación Simple'), ('return_refund', 'Devolución con Retorno')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('processing', 'Procesando'), ('completed', 'Completado'), ('rejected', 'Rechazado'), ('waiting_return', 'Esperando Devolución'), ('product_received', 'Producto Recibido'), ('quality_check', 'Verificando Calidad')], default='pending', max_length=20)),
                ('reason', models.CharField(choices=[('changed_mind', 'Cambié de opinión'), ('wrong_product', 'Producto incorrecto'), ('defective', 'Producto defectuoso'), ('not_as_described', 'No como se describía'), ('damaged_shipping', 'Dañado en envío'), ('other', 'Otro motivo')], max_length=20)),
                ('customer_notes', models.TextField(blank=True, null=True, verbose_name='Comentarios del cliente')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Notas del administrador')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto a reembolsar')),
                ('refund_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Com isión por reembolso')),
                ('final_refund_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto final de reembolso')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('return_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Fecha límite para devolver')),
                ('product_returned_at', models.DateTimeField(blank=True, null=True)),
                ('quality_approved', models.BooleanField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='store.order')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reembolso',
                'verbose_name_plural': 'Reembolsos',
                'ordering': ['-requested_at'],
            },
        ),
    ]
