# Generated by Django 5.1.6 on 2025-11-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_refund'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True, verbose_name='Subtítulo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='Imagen')),
                ('button_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Texto del botón')),
                ('button_link', models.URLField(blank=True, null=True, verbose_name='Enlace del botón')),
                ('external_link', models.BooleanField(default=False, verbose_name='¿Enlace externo?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
                ('slide_type', models.CharField(choices=[('promotion', '🏷️ Promoción/Oferta'), ('business', '🏢 Negocio/Instalaciones'), ('product', '🔧 Producto Destacado'), ('service', '⚙️ Servicio'), ('announcement', '📢 Anuncio General')], default='promotion', max_length=20, verbose_name='Tipo de slide')),
                ('background_color', models.CharField(default='#ffffff', help_text='Formato hex: #ffffff', max_length=7, verbose_name='Color de fondo')),
                ('text_color', models.CharField(default='#000000', help_text='Formato hex: #000000', max_length=7, verbose_name='Color del texto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(blank=True, help_text='Dejar vacío para mostrar inmediatamente', null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(blank=True, help_text='Dejar vacío para mostrar indefinidamente', null=True, verbose_name='Fecha de fin')),
            ],
            options={
                'verbose_name': 'Slide del Carrusel',
                'verbose_name_plural': 'Slides del Carrusel',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
