# Generated by Django 5.2.8 on 2025-11-19 03:56

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_carouselslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselslide',
            name='image',
            field=models.ImageField(upload_to=store.models.carousel_image_path, verbose_name='Imagen'),
        ),
    ]
