# Generated by Django 5.2.8 on 2025-11-19 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_alter_carouselslide_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Sucursal')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código de Sucursal')),
                ('address', models.CharField(max_length=300, verbose_name='Dirección')),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Colonia')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(choices=[('AGU', 'Aguascalientes'), ('BCN', 'Baja California'), ('BCS', 'Baja California Sur'), ('CAM', 'Campeche'), ('CHP', 'Chiapas'), ('CHH', 'Chihuahua'), ('COA', 'Coahuila'), ('COL', 'Colima'), ('DIF', 'Ciudad de México'), ('DUR', 'Durango'), ('GUA', 'Guanajuato'), ('GRO', 'Guerrero'), ('HGO', 'Hidalgo'), ('JAL', 'Jalisco'), ('MEX', 'Estado de México'), ('MIC', 'Michoacán'), ('MOR', 'Morelos'), ('NAY', 'Nayarit'), ('NLE', 'Nuevo León'), ('OAX', 'Oaxaca'), ('PUE', 'Puebla'), ('QRO', 'Querétaro'), ('QRO', 'Quintana Roo'), ('SLP', 'San Luis Potosí'), ('SIN', 'Sinaloa'), ('SON', 'Sonora'), ('TAB', 'Tabasco'), ('TAM', 'Tamaulipas'), ('TLX', 'Tlaxcala'), ('VER', 'Veracruz'), ('YUC', 'Yucatán'), ('ZAC', 'Zacatecas')], max_length=3, verbose_name='Estado')),
                ('zipcode', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('schedule', models.TextField(help_text='Ej: Lunes a Viernes 8:00-18:00', verbose_name='Horario de Atención')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('is_main', models.BooleanField(default=False, verbose_name='Sucursal Principal')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL, verbose_name='Encargado')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['-is_main', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Cantidad en Stock')),
                ('min_stock', models.IntegerField(default=5, verbose_name='Stock Mínimo')),
                ('max_stock', models.IntegerField(default=100, verbose_name='Stock Máximo')),
                ('location_code', models.CharField(blank=True, help_text='Ej: Pasillo A, Estante 3', max_length=50, null=True, verbose_name='Código de Ubicación')),
                ('last_restock_date', models.DateTimeField(blank=True, null=True, verbose_name='Última Reposición')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_branches', to='store.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_inventory', to='store.product')),
            ],
            options={
                'verbose_name': 'Inventario por Sucursal',
                'verbose_name_plural': 'Inventarios por Sucursal',
                'ordering': ['branch__name', 'product__name'],
                'unique_together': {('product', 'branch')},
            },
        ),
    ]
